language: node_js

node_js:
  - "0.8"
  - "0.10"
  - "0.11"

services:
  - redis-server

before_install:
  - test $TRAVIS_NODE_VERSION = '0.8' && npm install -g npm@1.2.8000 || true

before_script:
  - make

env: TRAVIS=1
